# Generated by Django 6.0.7 on 2026-09-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequest',
            name='normal_waste_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
