# Generated by Django 6.0.7 on 2026-09-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_app', '0002_wasterequest_normal_waste_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyWasteSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], unique=True)),
                ('waste_items', models.TextField(help_text='Enter waste items separated by commas')),
            ],
        ),
    ]
