# Generated by Django 6.0.7 on 2026-08-31 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(choices=[('NORMAL', 'Normal Waste'), ('SCRAP', 'Custom/Scrap Material')], default='NORMAL', max_length=10)),
                ('scrap_category', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.FloatField(blank=True, default=0.0, null=True)),
                ('calculated_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted by HKS'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=15)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.citizen')),
            ],
        ),
    ]
